// GSMPPP_CONFIG.H

#ifndef __GSMPPP_CONFIG_H__
#define __GSMPPP_CONFIG_H__

#define GSMPPP_MODEM_DEVICE_SIM800
//#define GSMPPP_MODEM_DEVICE_BG96
//#define GSMPPP_MODEM_DEVICE_SIM7600
//#define GSMPPP_MODEM_PPP_AUTH_USERNAME  "username"
//#define GSMPPP_MODEM_PPP_AUTH_PASSWORD  "password"
#define GSMPPP_MODEM_APN                "orange"
#define GSMPPP_MODEM_UART_TX_PIN  25
#define GSMPPP_MODEM_UART_RX_PIN 26
#define GSMPPP_MODEM_UART_RTS_PIN -1
#define GSMPPP_MODEM_UART_CTS_PIN -1
#define GSMPPP_MODEM_UART_RX_BUFFER_SIZE 1024
#define GSMPPP_MODEM_UART_TX_BUFFER_SIZE 512
#define GSMPPP_MODEM_UART_EVENT_QUEUE_SIZE 30
#define GSMPPP_MODEM_UART_EVENT_TASK_STACK_SIZE 2048
#define GSMPPP_MODEM_UART_EVENT_TASK_PRIORITY 5
#define GSMPPP_MODEM_UART_FLOW_CONTROL_NONE
//#define GSMPPP_MODEM_UART_FLOW_CONTROL_SW
//#define GSMPPP_MODEM_UART_FLOW_CONTROL_HW

#endif // #ifndef __GSMPPP_CONFIG_H__

